

export const DUMMY_MESSAGES = [
  {
    id: '1',
    sender: 'Premium Credit Solutions',
    initials: 'PC',
    image:require('../assest/img1.jpg'),
    avatarColor: '#EEF2FF',
    preview: "Payment confirmed! Your receipt will arrive in your email shortly.",
    time: '2hr ago',
    date: 'Today',
    unread: true,
    status: 'online',
  },
  {
    id: '2',
    sender: 'Standard Payment Services',
       image:require('../assest/img2.jpg'),
    initials: 'SP',
    avatarColor: '#FFF7ED',
    preview: "We got your request. It's under review, and you'll be notified once approved.",
    time: '7day ago',
    date: 'Today',
    unread: false,
    status: 'pending',
  },
  {
    id: '3',
    sender: 'Basic Financial Support',
    initials: 'BF',
       image:require('../assest/img3.jpg'),
    avatarColor: '#F0FDF4',
    preview: "Payment accepted successfully. A confirmation email and SMS are on the way.",
    time: '2day ago',
    date: 'Today',
    unread: false,
    status: 'offline',
  },
  {
    id: '4',
    sender: 'Nova Finance Group',
    initials: 'NF',
       image:require('../assest/img4.jpg'),
    avatarColor: '#FFF1F2',
    preview: "Your payment went through! We've sent a receipt to your registered email.",
    time: '3day ago',
    date: '12/10/24',
    unread: true,
    status: 'online',
  },

  {
    id: '5',
    sender: 'Atlas Credit Bureau',
       image:require('../assest/img1.jpg'),
    initials: 'AC',
    avatarColor: '#F0F9FF',
    preview: "Your credit score has been updated. Check the Home tab for details.",
    time: '5day ago',
    date: '12/10/24',
    unread: false,
    status: 'offline',
  },

];